"""
Script de prueba para el sistema de autenticación
Ejecutar con: python test_auth_flow.py
"""

print("=" * 60)
print("SISTEMA DE AUTENTICACIÓN FENIX - GUÍA DE PRUEBA")
print("=" * 60)

print("\n📋 PASO 1: REGISTRO DE USUARIO")
print("-" * 60)
print("1. Abre el navegador en: http://127.0.0.1:8000/accounts/register/")
print("2. Completa el formulario:")
print("   - Email: test@ejemplo.com")
print("   - Nombre: Usuario de Prueba")
print("   - Contraseña: test1234")
print("   - Idioma: Español")
print("3. Haz clic en 'Registrarse'")
print("4. ✅ Deberías ver: 'Registro exitoso. Por favor verifica tu email...'")
print("\n💡 VERIFICAR: El email con el token aparecerá en la consola del servidor")

print("\n📧 PASO 2: VERIFICACIÓN DE EMAIL")
print("-" * 60)
print("1. Ve a la consola donde corre el servidor Django")
print("2. Busca la línea que dice:")
print("   'Por favor, haz clic en el siguiente enlace...'")
print("3. Copia la URL completa (ejemplo):")
print("   http://127.0.0.1:8000/accounts/verify-email/?token=abc-123...")
print("4. Pega la URL en tu navegador")
print("5. ✅ Deberías ver: '¡Email verificado exitosamente!'")

print("\n🚫 PASO 3: LOGIN SIN APROBACIÓN")
print("-" * 60)
print("1. Ve a: http://127.0.0.1:8000/accounts/login/")
print("2. Ingresa:")
print("   - Email: test@ejemplo.com")
print("   - Contraseña: test1234")
print("3. Haz clic en 'Iniciar Sesión'")
print("4. ⚠️ Deberías ser redirigido a: /accounts/pending-approval/")
print("5. ✅ Verás: 'Cuenta Pendiente de Aprobación'")

print("\n👨‍💼 PASO 4: APROBACIÓN DE USUARIO (Como Admin)")
print("-" * 60)
print("1. Abre una nueva pestaña en: http://127.0.0.1:8000/accounts/login/")
print("2. Inicia sesión con el super admin:")
print("   - Email: admin@fenix.com")
print("   - Contraseña: (la que configuraste)")
print("3. Ve a: http://127.0.0.1:8000/accounts/approval/")
print("4. Verás la lista de usuarios pendientes")
print("5. Haz clic en 'Aprobar' junto a test@ejemplo.com")
print("6. ✅ Deberías ver: 'Usuario aprobado exitosamente'")
print("7. 💡 Se enviará un email de notificación (ver consola)")

print("\n✅ PASO 5: LOGIN EXITOSO")
print("-" * 60)
print("1. Cierra la sesión del admin")
print("2. Ve a: http://127.0.0.1:8000/accounts/login/")
print("3. Ingresa de nuevo:")
print("   - Email: test@ejemplo.com")
print("   - Contraseña: test1234")
print("4. ✅ ¡Ahora deberías entrar al sistema!")
print("5. Serás redirigido al catálogo de productos")

print("\n🔑 PASO 6 (OPCIONAL): RESTABLECIMIENTO DE CONTRASEÑA")
print("-" * 60)
print("1. Cierra sesión: http://127.0.0.1:8000/accounts/logout/")
print("2. En login, haz clic en '¿Olvidaste tu contraseña?'")
print("3. Ingresa: test@ejemplo.com")
print("4. Haz clic en 'Enviar Instrucciones'")
print("5. 💡 Ve a la consola y copia el enlace de reset")
print("6. Pega el enlace en el navegador")
print("7. Ingresa tu nueva contraseña")
print("8. ✅ Deberías ver: '¡Contraseña cambiada!'")
print("9. Inicia sesión con la nueva contraseña")

print("\n🔄 PASO 7 (OPCIONAL): REENVÍO DE EMAIL")
print("-" * 60)
print("1. Crea un nuevo usuario sin verificar el email")
print("2. Intenta hacer login")
print("3. Serás redirigido a /accounts/email-verification/")
print("4. Haz clic en 'Reenviar Email de Verificación'")
print("5. ✅ Deberías ver: 'Email de confirmación enviado'")
print("6. 💡 Un nuevo email aparecerá en la consola")
print("7. Si intentas reenviar de nuevo < 5 min, verás:")
print("   'Ya se envió un email recientemente. Por favor espera...'")

print("\n🎨 CARACTERÍSTICAS DE LA UI")
print("-" * 60)
print("✨ Login mejorado:")
print("   - Iconos en los campos (📧 email, 🔒 contraseña)")
print("   - Botón para mostrar/ocultar contraseña (👁️)")
print("   - Enlace 'Olvidaste tu contraseña' visible")
print("   - Diseño con tarjetas modernas")
print("\n✨ Páginas informativas:")
print("   - Email Verification: con botón de reenvío")
print("   - Pending Approval: con explicación del proceso")
print("   - Password Reset: flujo completo con 4 pasos")

print("\n🛠️ DJANGO ADMIN")
print("-" * 60)
print("1. Ve a: http://127.0.0.1:8000/admin/")
print("2. Inicia sesión con super admin")
print("3. Navega a 'Users':")
print("   - Ver todos los usuarios")
print("   - Ver estado: email_verified, pending_approval")
print("   - Editar manualmente cualquier campo")
print("4. Navega a 'Email Verification Tokens':")
print("   - Ver todos los tokens generados")
print("   - Ver cuáles están usados o expirados")
print("   - Filtrar por usuario")

print("\n📊 ESTADOS DEL SISTEMA")
print("-" * 60)
print("Estado 1: Recién Registrado")
print("  └─ email_verified: False")
print("  └─ pending_approval: True")
print("  └─ Acción: Verificar email")
print("\nEstado 2: Email Verificado")
print("  └─ email_verified: True")
print("  └─ pending_approval: True")
print("  └─ Acción: Esperar aprobación")
print("\nEstado 3: Usuario Activo")
print("  └─ email_verified: True")
print("  └─ pending_approval: False")
print("  └─ is_active: True")
print("  └─ ✅ Puede usar el sistema")

print("\n⚠️ CASOS ESPECIALES")
print("-" * 60)
print("Managers y Super Admins:")
print("  → Pueden entrar aunque pending_approval = True")
print("  → Saltean el flujo de aprobación")
print("\nUsuarios Desactivados:")
print("  → is_active = False")
print("  → No pueden entrar bajo ninguna circunstancia")
print("  → Requieren reactivación por admin")

print("\n📝 LOGS Y AUDITORÍA")
print("-" * 60)
print("Todas las acciones importantes se registran en AuditLog:")
print("  - Aprobación de usuarios")
print("  - Cambios de estado")
print("  - IP del usuario")
print("  - User agent")
print("  - Timestamp")
print("\nVer en admin: Core → Audit Logs")

print("\n" + "=" * 60)
print("🚀 ¡SISTEMA LISTO PARA PRUEBAS!")
print("=" * 60)
print("\n📖 Para más detalles, consulta: AUTHENTICATION_SYSTEM.md")
print("🌐 Servidor: http://127.0.0.1:8000/")
print("👨‍💻 Admin: http://127.0.0.1:8000/admin/")
print("\n")
