# Generated by Django 6.0.1 on 2026-01-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_language', models.CharField(choices=[('es', 'Español'), ('zh-hans', 'Chinese (Simplified)')], default='es', help_text='Idioma por defecto de la plataforma (fallback)', max_length=10)),
                ('email_from', models.EmailField(default='noreply@fenix.com', help_text='Email remitente para notificaciones', max_length=254)),
                ('email_from_name', models.CharField(default='FENIX', help_text='Nombre del remitente', max_length=200)),
                ('default_delivery_window_hours', models.PositiveIntegerField(default=24, help_text='Ventana de entrega por defecto (horas)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
