# Generated by Django 6.0.1 on 2026-02-03 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_login', 'Inicio de sesión'), ('user_logout', 'Cierre de sesión'), ('user_approved', 'Usuario aprobado'), ('user_rejected', 'Usuario rechazado'), ('order_created', 'Pedido creado'), ('order_status_changed', 'Estado de pedido cambiado'), ('order_eta_updated', 'ETA actualizado'), ('product_created', 'Producto creado'), ('product_updated', 'Producto actualizado'), ('product_deleted', 'Producto eliminado'), ('stock_updated', 'Stock actualizado'), ('document_uploaded', 'Documento subido'), ('document_deleted', 'Documento eliminado')], max_length=50, verbose_name='Acción')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('object_type', models.CharField(blank=True, help_text='Tipo de modelo afectado (Order, Product, User, etc.)', max_length=50, verbose_name='Tipo de objeto')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_auditl_created_1a76fa_idx'), models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx'), models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx')],
            },
        ),
    ]
