# Generated by Django 6.0.2 on 2026-04-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platformsettings_order_notification_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('asunto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('acepta_privacidad', models.BooleanField(default=False, verbose_name='Acepta política de privacidad')),
                ('acepta_comunicaciones', models.BooleanField(default=False, verbose_name='Acepta comunicaciones comerciales')),
                ('origen', models.CharField(default='formulario_contacto_web', max_length=100, verbose_name='Origen')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('descartado', 'Descartado')], default='nuevo', max_length=20, verbose_name='Estado')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadatos adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Lead de contacto',
                'verbose_name_plural': 'Leads de contacto',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_contac_created_ff92d6_idx'), models.Index(fields=['email'], name='core_contac_email_24fded_idx'), models.Index(fields=['estado'], name='core_contac_estado_13f960_idx')],
            },
        ),
    ]
