# Generated by Django 6.0.7 on 2026-07-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_privacyrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_login', 'Inicio de sesión'), ('user_logout', 'Cierre de sesión'), ('user_approved', 'Usuario aprobado'), ('user_rejected', 'Usuario rechazado'), ('order_created', 'Pedido creado'), ('order_status_changed', 'Estado de pedido cambiado'), ('order_eta_updated', 'ETA actualizado'), ('product_created', 'Producto creado'), ('product_updated', 'Producto actualizado'), ('product_deleted', 'Producto eliminado'), ('stock_updated', 'Stock actualizado'), ('document_uploaded', 'Documento subido'), ('document_deleted', 'Documento eliminado'), ('personal_data_exported', 'Datos personales exportados'), ('user_disabled', 'Usuario desactivado'), ('crm_lead_archived', 'Lead de CRM archivado'), ('crm_leads_archived', 'Leads de CRM archivados')], max_length=50, verbose_name='Acción'),
        ),
    ]
