# Generated by Django 6.0.1 on 2026-02-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_company_historicalcompany_usercompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organización', 'verbose_name_plural': 'Organizaciones'},
        ),
    ]
