"""
Django settings for fenix project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Configurar codificación UTF-8 en Windows
if sys.platform == 'win32':
    if sys.getdefaultencoding() != 'utf-8':
        os.environ['PYTHONIOENCODING'] = 'utf-8'
        # Asegurar que los archivos se lean con UTF-8
        import locale
        locale.setlocale(locale.LC_ALL, '')

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-3v^@+j7ha%j%)+b(6ad%s@@!eh#30=0z^()nhgjj^dvx-0q8+w')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'true').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'simple_history',  # Auditoría de cambios
    'accounts',
    'catalog',
    'orders',
    'recurring',
    'notifications',
    'core',  # Configuración global de plataforma
    'whatsapp',  # Integración WhatsApp Business Cloud API
    'organizations',  # Gestión de empresas y multitenancy
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',  # Auditoría de cambios
    'accounts.middleware.UserApprovalMiddleware',  # Bloquea acceso si pending_approval=True
    'accounts.middleware.SessionTrackingMiddleware',  # Tracking de sesiones
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fenix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': DEBUG,  # Deshabilita caché de templates en desarrollo
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'orders.context_processors.cart_count',
                'accounts.context_processors.user_language',  # Idioma del usuario
                'accounts.context_processors.user_greeting',  # Saludo inteligente
            ],
        },
    },
]

WSGI_APPLICATION = 'fenix.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Supabase PostgreSQL por defecto. Si USE_SQLITE_DEV=True en .env, usamos SQLite
# (útil cuando Supabase no conecta y runserver se queda colgado).

_use_sqlite_dev = os.getenv('USE_SQLITE_DEV', '').lower() in ('1', 'true', 'yes')

if _use_sqlite_dev:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    _db_opts = {}
    if os.getenv('DB_HOST') and os.getenv('DB_HOST') != 'localhost':
        _db_opts['sslmode'] = 'require'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': _db_opts,
        }
    }

# Email (notificaciones)
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if not os.getenv('EMAIL_HOST') else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@fenix.com')
DEFAULT_ORDER_NOTIFICATION_EMAIL = os.getenv('DEFAULT_ORDER_NOTIFICATION_EMAIL', 'plataformafenix2026@gmail.com')
DEFAULT_ORDER_CURRENCY = os.getenv('DEFAULT_ORDER_CURRENCY', 'EUR')

# Admin email para notificaciones de aprobación
ADMIN_APPROVAL_EMAIL = os.getenv('ADMIN_APPROVAL_EMAIL', 'admin@fenix.com')

# Lista de administradores (también se puede usar para notificaciones)
ADMINS = [
    ('Admin Fenix', os.getenv('ADMIN_APPROVAL_EMAIL', 'admin@fenix.com')),
]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

LANGUAGES = [
    ('es', 'Español'),
    ('zh-hans', '中文 (简体)'),
    # ('en', 'English'),  # Oculto temporalmente
]

# Configuración de cookies de idioma
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 365  # 1 año
LANGUAGE_COOKIE_HTTPONLY = True
LANGUAGE_COOKIE_SAMESITE = 'Lax'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (imágenes subidas por usuarios)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

# Mantén la configuración anterior como referencia en .env para evitar sobreescrituras involuntarias
