# Generated by Django 6.0.1 on 2026-02-03 22:48

from django.db import migrations


def update_role_values(apps, schema_editor):
    """
    Actualiza los valores de roles antiguos a los nuevos:
    - 'manager' -> 'admin'
    - 'client' -> 'user'
    """
    User = apps.get_model('accounts', 'User')
    
    # Actualizar 'manager' a 'admin'
    updated_manager = User.objects.filter(role='manager').update(role='admin')
    
    # Actualizar 'client' a 'user'
    updated_client = User.objects.filter(role='client').update(role='user')
    
    print(f"✅ Migración de roles completada:")
    print(f"   - {updated_manager} usuarios 'manager' → 'admin'")
    print(f"   - {updated_client} usuarios 'client' → 'user'")


def reverse_update_role_values(apps, schema_editor):
    """
    Revierte los cambios de roles (para rollback):
    - 'admin' -> 'manager'
    - 'user' -> 'client'
    """
    User = apps.get_model('accounts', 'User')
    
    # Revertir 'admin' a 'manager'
    User.objects.filter(role='admin').update(role='manager')
    
    # Revertir 'user' a 'client'
    User.objects.filter(role='user').update(role='client')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sync_user_status'),
    ]

    operations = [
        migrations.RunPython(update_role_values, reverse_update_role_values),
    ]

