# Generated by Django 6.0.1 on 2026-02-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_avatar_user_first_name_user_last_login_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Token de Verificación', 'verbose_name_plural': 'Tokens de Verificación'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad del local (OBLIGATORIO)', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='user',
            name='ciudad_entrega',
            field=models.CharField(blank=True, help_text='Ciudad de entrega (OBLIGATORIO)', max_length=100, verbose_name='Ciudad entrega'),
        ),
        migrations.AddField(
            model_name='user',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Código postal del local (OBLIGATORIO)', max_length=10, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='user',
            name='codigo_postal_entrega',
            field=models.CharField(blank=True, help_text='Código postal de entrega (OBLIGATORIO)', max_length=10, verbose_name='Código postal entrega'),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion_entrega',
            field=models.CharField(blank=True, help_text='Dirección donde se realizará la entrega (OBLIGATORIO)', max_length=300, verbose_name='Dirección de entrega'),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion_local',
            field=models.CharField(blank=True, help_text='Dirección fiscal o del local (OBLIGATORIO)', max_length=300, verbose_name='Dirección local'),
        ),
        migrations.AddField(
            model_name='user',
            name='items_count',
            field=models.IntegerField(default=0, help_text='Número de items en el perfil operativo', verbose_name='Contador de items'),
        ),
        migrations.AddField(
            model_name='user',
            name='observaciones_entrega',
            field=models.TextField(blank=True, help_text='Instrucciones especiales para la entrega (opcional)', verbose_name='Observaciones de entrega'),
        ),
        migrations.AddField(
            model_name='user',
            name='pais',
            field=models.CharField(default='España', help_text='País del local', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Indica si el perfil operativo está completo para realizar pedidos', verbose_name='Perfil completado'),
        ),
        migrations.AddField(
            model_name='user',
            name='provincia',
            field=models.CharField(blank=True, help_text='Provincia del local (OBLIGATORIO)', max_length=100, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='user',
            name='provincia_entrega',
            field=models.CharField(blank=True, help_text='Provincia de entrega (OBLIGATORIO)', max_length=100, verbose_name='Provincia entrega'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono_empresa',
            field=models.CharField(blank=True, help_text='Teléfono de contacto de la empresa', max_length=20, verbose_name='Teléfono empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono_reparto',
            field=models.CharField(blank=True, help_text='Teléfono de contacto para el reparto (OBLIGATORIO)', max_length=20, verbose_name='Teléfono reparto'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_entrega',
            field=models.CharField(blank=True, choices=[('recogida', 'Recogida en local'), ('envio', 'Envío a domicilio')], help_text='Método de entrega preferido (OBLIGATORIO)', max_length=20, verbose_name='Tipo de entrega'),
        ),
        migrations.AddField(
            model_name='user',
            name='ventana_entrega',
            field=models.CharField(blank=True, help_text='Horario o ventana de entrega preferida (opcional)', max_length=200, verbose_name='Ventana de entrega'),
        ),
    ]
