# Generated by Django 6.0.1 on 2026-02-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_emailverificationtoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitysettings',
            name='api_token',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
