# Generated by Django 6.0.7 on 2026-07-24 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_isolated_customer_organizations(apps, schema_editor):
    """Crea una organización distinta por usuario; nunca infiere fusiones."""
    User = apps.get_model('accounts', 'User')
    Organization = apps.get_model('accounts', 'CustomerOrganization')
    Membership = apps.get_model(
        'accounts',
        'CustomerOrganizationMembership',
    )

    client_users = User.objects.filter(
        role='user',
        is_staff=False,
        is_superuser=False,
    ).order_by('pk')
    for user in client_users.iterator():
        name = (
            (user.company or '').strip()
            or (user.full_name or '').strip()
            or user.email.split('@', 1)[0]
        )[:200]
        organization = Organization.objects.create(
            name=name,
            legal_name=(user.company or '').strip()[:250],
            tax_id=(user.vat_number or '').strip()[:30],
            status='active',
        )
        Membership.objects.create(
            organization=organization,
            user=user,
            role='owner',
            status='active',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_private_avatars'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Empresa cliente')),
                ('legal_name', models.CharField(blank=True, max_length=250, verbose_name='Razón social')),
                ('tax_id', models.CharField(blank=True, max_length=30, verbose_name='CIF/NIF')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa cliente',
                'verbose_name_plural': 'Empresas cliente',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('member', 'Miembro')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('invited', 'Invitada'), ('disabled', 'Deshabilitada')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.customerorganization', verbose_name='Empresa cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='organization_membership', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pertenencia a empresa',
                'verbose_name_plural': 'Pertenencias a empresas',
                'indexes': [models.Index(fields=['organization', 'status'], name='accounts_cu_organiz_6c04ff_idx')],
            },
        ),
        migrations.RunPython(
            backfill_isolated_customer_organizations,
            migrations.RunPython.noop,
        ),
    ]
