# Generated by Django 6.0.2 on 2026-04-28 12:40

from django.db import migrations, models
from pgvector.django import VectorExtension, VectorField

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenido de texto del fragmento de conocimiento.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional (ej: id_producto, categoría, fuente).')),
                ('embedding', VectorField(blank=True, dimensions=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base de Conocimiento',
                'verbose_name_plural': 'Bases de Conocimiento',
            },
        ),
    ]
