# Generated by Django 6.0.2 on 2026-05-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_alter_knowledgebase_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_prefix', models.CharField(default='+34', max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('email_verified', models.BooleanField(default=False)),
                ('queries_used', models.IntegerField(default=0)),
                ('last_query_at', models.DateTimeField(auto_now=True)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
