# Generated by Django 6.0.2 on 2026-05-09 16:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('channel', models.CharField(choices=[('web_assistant', 'Asistente Web'), ('whatsapp', 'WhatsApp'), ('contact_form', 'Formulario de Contacto'), ('manual', 'Manual')], default='web_assistant', max_length=30, verbose_name='Canal')),
                ('source', models.CharField(blank=True, help_text='Ej: Fenix Assistant (OTP), WhatsApp Web Form, etc.', max_length=255, null=True, verbose_name='Origen Detallado')),
                ('first_message', models.TextField(blank=True, null=True, verbose_name='Primer Mensaje')),
                ('lead_status', models.CharField(choices=[('nuevo', 'Nuevo'), ('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('presupuesto_enviado', 'Presupuesto Enviado'), ('convertido', 'Convertido'), ('perdido', 'Perdido'), ('sin_respuesta', 'Sin Respuesta')], default='nuevo', max_length=30, verbose_name='Estado Comercial')),
                ('validation_status', models.CharField(choices=[('nuevo', 'Nuevo'), ('validado', 'Validado'), ('atendido', 'Atendido'), ('descartado', 'Descartado/Spam')], default='nuevo', max_length=30, verbose_name='Estado de Validación')),
                ('priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20, verbose_name='Prioridad')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Estimado (€)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Comerciales')),
                ('geographic_zone', models.CharField(blank=True, help_text='Ej: Madrid, Barcelona, Toledo...', max_length=150, null=True, verbose_name='Zona Geográfica')),
                ('last_contact_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Último Contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crm_leads', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
            ],
            options={
                'verbose_name': 'Lead de CRM',
                'verbose_name_plural': 'Leads de CRM',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMLeadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('web_assistant', 'Asistente Web'), ('whatsapp', 'WhatsApp'), ('contact_form', 'Formulario de Contacto'), ('manual', 'Manual')], max_length=30, verbose_name='Canal')),
                ('sender', models.CharField(choices=[('lead', 'Lead'), ('agent', 'Agente Comercial'), ('system', 'Sistema'), ('ai', 'Asistente IA')], default='lead', max_length=20, verbose_name='Remitente')),
                ('message', models.TextField(verbose_name='Mensaje / Nota / Acción')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('metadata', models.JSONField(blank=True, help_text='Estructura flexible para guardar payloads de webhook, etc.', null=True, verbose_name='Metadatos Adicionales')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.crmlead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Mensaje de Lead',
                'verbose_name_plural': 'Historial de Mensajes',
                'ordering': ['timestamp'],
            },
        ),
    ]
