# Generated by Django 6.0.1 on 2026-02-16 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_alter_product_created_at_and_more'),
        ('recurring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pedido Recurrente', 'verbose_name_plural': 'Pedidos Recurrentes'},
        ),
        migrations.AlterModelOptions(
            name='recurringorderitem',
            options={'verbose_name': 'Línea de Pedido Recurrente', 'verbose_name_plural': 'Líneas de Pedidos Recurrentes'},
        ),
        migrations.AlterField(
            model_name='recurringorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='recurringorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='recurringorder',
            name='delivery_window_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Ventana Entrega (horas)'),
        ),
        migrations.AlterField(
            model_name='recurringorder',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='recurringorder',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Diaria'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], max_length=20, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='recurringorder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='recurringorder',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próxima Ejecución'),
        ),
        migrations.AlterField(
            model_name='recurringorder',
            name='start_date',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='recurringorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_items', to='catalog.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='recurringorderitem',
            name='product_name_es',
            field=models.CharField(max_length=200, verbose_name='Nombre (ES)'),
        ),
        migrations.AlterField(
            model_name='recurringorderitem',
            name='product_name_zh_hans',
            field=models.CharField(max_length=200, verbose_name='Nombre (中文)'),
        ),
        migrations.AlterField(
            model_name='recurringorderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='recurringorderitem',
            name='recurring_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recurring.recurringorder', verbose_name='Pedido Recurrente'),
        ),
    ]
