# Generated by Django 6.0.7 on 2026-07-24 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_recurring_order_organizations(apps, schema_editor):
    RecurringOrder = apps.get_model('recurring', 'RecurringOrder')
    Membership = apps.get_model(
        'accounts',
        'CustomerOrganizationMembership',
    )
    for customer_id, organization_id in Membership.objects.values_list(
        'user_id',
        'organization_id',
    ).iterator():
        RecurringOrder.objects.filter(
            customer_id=customer_id,
            organization_id__isnull=True,
        ).update(organization_id=organization_id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customerorganization_customerorganizationmembership'),
        ('recurring', '0002_alter_recurringorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringorder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_orders', to='accounts.customerorganization', verbose_name='Empresa cliente'),
        ),
        migrations.RunPython(
            backfill_recurring_order_organizations,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='recurringorder',
            index=models.Index(fields=['organization', 'is_active'], name='recurring_org_active_idx'),
        ),
    ]
