# Generated by Django 6.0.1 on 2026-01-24 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=200)),
                ('name_zh_hans', models.CharField(max_length=200)),
                ('description_es', models.TextField(blank=True)),
                ('description_zh_hans', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_available', models.IntegerField(default=0)),
                ('stock_min_threshold', models.IntegerField(default=0)),
                ('stock_status', models.CharField(choices=[('ok', 'OK'), ('low', 'Bajo stock'), ('out', 'Sin stock')], default='ok', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
