# Generated by Django 6.0.1 on 2026-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name_es'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Descripción (ES)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_zh_hans',
            field=models.TextField(blank=True, verbose_name='Descripción (中文)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del producto (recomendado: 800x600px)', null=True, upload_to='products/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_es',
            field=models.CharField(max_length=200, verbose_name='Nombre (ES)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_zh_hans',
            field=models.CharField(max_length=200, verbose_name='Nombre (中文)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_available',
            field=models.IntegerField(default=0, verbose_name='Stock Disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_min_threshold',
            field=models.IntegerField(default=0, verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('ok', 'OK'), ('low', 'Bajo stock'), ('out', 'Sin stock')], default='ok', max_length=10, verbose_name='Estado Stock'),
        ),
    ]
