# Generated by Django 6.0.1 on 2026-03-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_display',
            field=models.CharField(blank=True, help_text='Ejemplo: "100 g", "1 Kg", "Unidad". Aparecerá junto al precio: 1,00€ / 100 g', max_length=50, null=True, verbose_name='Unidad de medida'),
        ),
    ]
