# Generated by Django 6.0.1 on 2026-03-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_is_best_seller_product_is_new_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['catalog_order', 'name_es'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='catalog_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden en catálogo'),
        ),
    ]
