# Generated by Django 6.0.1 on 2026-03-09 19:46

from django.db import migrations


def initialize_catalog_order(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    products = Product.objects.all().order_by('id')
    for i, product in enumerate(products):
        product.catalog_order = i + 1
        product.save(update_fields=['catalog_order'])

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_options_product_catalog_order'),
    ]

    operations = [
        migrations.RunPython(initialize_catalog_order, reverse_code=migrations.RunPython.noop),
    ]
