# Generated by Django 6.0.1 on 2026-03-11 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_initialize_catalog_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_title', models.CharField(max_length=200, verbose_name='Título promocional')),
                ('promo_image', models.ImageField(help_text='Imagen que aparecerá en el hero de la Home', upload_to='promotions/', verbose_name='Imagen promocional')),
                ('promo_label', models.CharField(blank=True, choices=[('oferta_semana', 'Oferta de la semana'), ('pack', 'Pack'), ('mas_vendido', 'Más vendido'), ('estrella', 'Producto estrella'), ('novedad', 'Novedad'), ('oferta_flash', 'Oferta flash'), ('super_oferta', 'Super oferta'), ('limitada', 'Edición limitada'), ('navidad', 'Especial Navidad'), ('verano', 'Especial verano'), ('barbacoa', 'Ideal para barbacoas'), ('recomendado', 'Producto recomendado'), ('mejor_precio', 'Mejor precio')], max_length=50, null=True, verbose_name='Etiqueta promocional')),
                ('promo_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de promoción')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto Promocional',
                'verbose_name_plural': 'Productos Promocionales',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
