# Generated by Django 6.0.1 on 2026-03-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_promotionalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalproduct',
            name='target_category',
            field=models.CharField(blank=True, help_text='Slug de la categoría en el catálogo (ej: jamon-curado, packs). Si se deja vacío, se intentará derivar automáticamente.', max_length=100, null=True, verbose_name='Categoría de destino'),
        ),
    ]
