# Generated by Django 6.0.1 on 2026-03-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_promotionalproduct_target_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalproduct',
            name='target_query',
            field=models.CharField(blank=True, help_text='Término de búsqueda para filtrar el catálogo (ej: Chorizo, Pack 10 sandwiches).', max_length=200, null=True, verbose_name='Búsqueda específica'),
        ),
        migrations.AlterField(
            model_name='promotionalproduct',
            name='target_category',
            field=models.CharField(blank=True, help_text='Slug de la categoría en el catálogo (ej: jamon-curado, packs).', max_length=100, null=True, verbose_name='Categoría de destino'),
        ),
    ]
