# Generated by Django 6.0.1 on 2026-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_promotionalproduct_target_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, help_text='Código único del producto (SKU)', max_length=50, null=True, unique=True, verbose_name='Referencia'),
        ),
    ]
