# Generated by Django 6.0.1 on 2026-03-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_label',
            field=models.CharField(blank=True, choices=[('oferta_semana', 'Oferta de la semana'), ('pack', 'Pack'), ('mas_vendido', 'Más vendido'), ('estrella', 'Producto estrella'), ('novedad', 'Novedad'), ('oferta_flash', 'Oferta flash'), ('super_oferta', 'Super oferta'), ('limitada', 'Edición limitada'), ('navidad', 'Especial Navidad'), ('verano', 'Especial verano'), ('barbacoa', 'Ideal para barbacoas'), ('recomendado', 'Producto recomendado'), ('mejor_precio', 'Mejor precio')], max_length=50, null=True, verbose_name='Etiqueta promocional'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, verbose_name='Más Vendido (Legacy)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Es Nuevo (Legacy)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(default=False, verbose_name='En Oferta (Legacy)'),
        ),
    ]
