# Generated by Django 6.0.2 on 2026-03-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_promo_label_alter_product_is_best_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalproduct',
            name='promo_image',
            field=models.ImageField(blank=True, help_text='Imagen que aparecerá en el hero de la Home (Opcional, se usará la del producto si está vacío)', null=True, upload_to='promotions/', verbose_name='Imagen promocional'),
        ),
        migrations.AlterField(
            model_name='promotionalproduct',
            name='promo_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título promocional'),
        ),
    ]
