# Generated by Django 6.0.2 on 2026-05-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_promotionalproduct_promo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Descripción Generada por IA'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_last_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Generación de Descripción'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('image_ocr', 'Análisis de Imagen (OCR)'), ('ai_enriched', 'Enriquecido por IA')], default='manual', max_length=50, verbose_name='Origen de la Descripción'),
        ),
    ]
