# Generated by Django 6.0.1 on 2026-03-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('page_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la página')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('sent_successfully', models.BooleanField(default=False, verbose_name='Enviado correctamente')),
                ('api_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta de la API')),
            ],
            options={
                'verbose_name': 'Lead de WhatsApp',
                'verbose_name_plural': 'Leads de WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
