# Generated by Django 6.0.1 on 2026-02-14 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_alter_product_created_at_and_more'),
        ('orders', '0003_orderdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={'ordering': ['created_at'], 'verbose_name': 'Evento de Pedido', 'verbose_name_plural': 'Eventos de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Línea de Pedido', 'verbose_name_plural': 'Líneas de Pedido'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el pedido fue entregado (auto-set cuando status=DELIVERED)', null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='eta_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETA Fin'),
        ),
        migrations.AlterField(
            model_name='order',
            name='eta_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETA Inicio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('confirmed', 'Confirmado'), ('preparing', 'Preparando'), ('out_for_delivery', 'En reparto'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='new', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='True cuando el stock se ha descontado al pasar a Preparando', verbose_name='Stock Descontado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_events', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='note',
            field=models.TextField(blank=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('confirmed', 'Confirmado'), ('preparing', 'Preparando'), ('out_for_delivery', 'En reparto'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Línea'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name_es',
            field=models.CharField(max_length=200, verbose_name='Nombre (ES)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name_zh_hans',
            field=models.CharField(max_length=200, verbose_name='Nombre (中文)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario'),
        ),
    ]
