# Generated by Django 6.0.7 on 2026-07-24 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_order_organizations(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Membership = apps.get_model(
        'accounts',
        'CustomerOrganizationMembership',
    )
    for customer_id, organization_id in Membership.objects.values_list(
        'user_id',
        'organization_id',
    ).iterator():
        Order.objects.filter(
            customer_id=customer_id,
            organization_id__isnull=True,
        ).update(organization_id=organization_id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customerorganization_customerorganizationmembership'),
        ('orders', '0005_private_order_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.customerorganization', verbose_name='Empresa cliente'),
        ),
        migrations.RunPython(
            backfill_order_organizations,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='order_org_status_created_idx'),
        ),
    ]
