# Generated by Django 6.0.1 on 2026-01-24 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_created', 'Pedido creado'), ('order_confirmed', 'Pedido confirmado'), ('order_out_for_delivery', 'En reparto'), ('order_delivered', 'Entregado'), ('order_cancelled', 'Cancelado'), ('eta_updated', 'ETA modificada'), ('order_late', 'Pedido fuera de ETA')], max_length=40)),
                ('subject_es', models.CharField(max_length=200)),
                ('subject_zh_hans', models.CharField(max_length=200)),
                ('message_es', models.TextField()),
                ('message_zh_hans', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
