# Generated by Django 6.0.1 on 2026-02-16 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Pedido creado'), ('order_confirmed', 'Pedido confirmado'), ('order_out_for_delivery', 'En reparto'), ('order_delivered', 'Entregado'), ('order_cancelled', 'Cancelado'), ('eta_updated', 'ETA modificada'), ('order_late', 'Pedido fuera de ETA')], max_length=40, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_es',
            field=models.TextField(verbose_name='Mensaje (ES)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_zh_hans',
            field=models.TextField(verbose_name='Mensaje (中文)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject_es',
            field=models.CharField(max_length=200, verbose_name='Asunto (ES)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject_zh_hans',
            field=models.CharField(max_length=200, verbose_name='Asunto (中文)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
